channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - click=7.1.*
  - matplotlib >=3.0.0,<4.0
  - numpy >=1.0,<2.0
  - pandas >=1.1,<1.3
  - pillow >=8.0,<9.0
  - python=3.7.*
  - pytorch=1.7.*
  - scikit-image >=0.17,<1.0
  - scikit-learn >=0.20,<1.0
  - scipy >=1.0,<2.0
  - seaborn=0.11.*
  - shapely=1.7.*
  - tqdm >=4.0,<5.0
